openapi: 3.0.3
info:
  title: NBG CIP Organization API
  version: "0.1"
  description: This is the API for managing organizations in the NBG CIP system provided
   on the integration layer.
servers:
- url: https://api.server.test/v1
paths:
  /organizations:
    get:
      summary: Get all organizations
      operationId: organizations_get
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationList'
      x-openapi-router-controller: swagger_server.controllers.default_controller
    post:
      summary: Create a new organization
      operationId: organizations_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
        required: true
      responses:
        "201":
          description: Organization created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /organizations/{organizationId}:
    put:
      summary: Update an existing organization
      operationId: organizations_organization_id_put
      parameters:
      - name: organizationId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
        required: true
      responses:
        "200":
          description: Organization updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
      x-openapi-router-controller: swagger_server.controllers.default_controller
    delete:
      summary: Delete an organization
      operationId: organizations_organization_id_delete
      parameters:
      - name: organizationId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Organization deleted successfully
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    OrganizationList:
      type: array
      items:
        $ref: '#/components/schemas/Organization'
    Organization:
      required:
      - id
      - name
      type: object
      properties:
        organizationid:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        email:
          type: string
          format: email
      example:
        organizationid: organizationid
        address:
          country: Example Country
          city: Example City
          street: Example Street
          postalCode: "12345"
          houseNumber: "123"
          state: EX
        name: name
        email: ""
    Address:
      type: object
      properties:
        houseNumber:
          type: string
          example: "123"
        street:
          type: string
          example: Example Street
        city:
          type: string
          example: Example City
        state:
          type: string
          example: EX
        postalCode:
          type: string
          example: "12345"
        country:
          type: string
          example: Example Country
      example:
        country: Example Country
        city: Example City
        street: Example Street
        postalCode: "12345"
        houseNumber: "123"
        state: EX

