openapi: 3.0.3
info:
  title: NBG CIP Organization API
  version: "0.1"
  description: This is the API for managing organizations in the NBG CIP system provided
   on the integration layer. It allows to create, update, delete and retrieve organizations 
   and related customers. Find more information at [Confluence](https://teampenta-dortmund.atlassian.net/wiki/x/BQBSlw).
servers:
  - url: https://api.server.test/v1
paths:
  /organizations:
    get:
      summary: Get a list of organizations
      responses:
        '200':
          description: A list of organizations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationList'
    post:
      summary: Create a new organization
      responses:
        '201':
          description: Organization created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
  /organizations/{organizationId}:
    get:
      summary: Get an organization by ID
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Organization details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
    put:
      summary: Update an organization
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Organization'
      responses:
        '200':
          description: Organization updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
    delete:
      summary: Delete an organization
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Organization deleted successfully
  /organizations/{organizationId}/buyers:
    get:
      summary: Get all buyers for a specific organization
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of buyers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Buyer'
    post:
      summary: Add one or more buyers to an existing organization
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Buyer'
      responses:
        '200':
          description: Buyers added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Organization'
  /organizations/{organizationId}/buyers/{buyerId}:
    get:
      summary: Get a buyer by ID
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
        - name: buyerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Buyer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Buyer'
    put:
      summary: Update a buyer
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
        - name: buyerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Buyer'
      responses:
        '200':
          description: Buyer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Buyer'
    delete:
      summary: Delete a buyer
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: string
        - name: buyerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Buyer deleted successfully
components:
  schemas:
    OrganizationList:
      type: array
      items:
        $ref: '#/components/schemas/Organization'
    Organization:
      type: object
      properties:
        organizationid:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        email:
          type: string
          format: email
        buyers:
          type: array
          items:
            $ref: '#/components/schemas/Buyer'
    Address:
      type: object
      properties:
        houseNumber:
          type: string
        street:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
        country:
          type: string
    Buyer:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
          format: email
