openapi: 3.0.3
info:
  title: NBG CIP Product API
  version: "1.0"
servers:
- url: https://api.server.test/v1
paths:
  /products:
    get:
      summary: Get all products
      operationId: products_get
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
      x-openapi-router-controller: swagger_server.controllers.product_controller
    post:
      summary: Create a new product
      operationId: products_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      x-openapi-router-controller: swagger_server.controllers.product_controller
  /products/{productId}:
    get:
      summary: Get a product by ID
      operationId: products_product_id_get
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      x-openapi-router-controller: swagger_server.controllers.product_controller
    put:
      summary: Update an existing product
      operationId: products_product_id_put
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        "200":
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      x-openapi-router-controller: swagger_server.controllers.product_controller
    delete:
      summary: Delete a product by ID
      operationId: products_product_id_delete
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Product deleted successfully
      x-openapi-router-controller: swagger_server.controllers.product_controller
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        attributes:
          $ref: '#/components/schemas/ProductAttributes'
        variants:
          type: array
          items:
            $ref: '#/components/schemas/ProductVariants'
    ProductAttributes:
      type: object
      properties:
        color:
          type: string
        size:
          type: string
        weight:
          type: number
    ProductVariants:
      type: object
      properties:
        variantId:
          type: string
        variantName:
          type: string
        variantAttributes:
          $ref: '#/components/schemas/ProductAttributes'
    ProductList:
      type: array
      items:
        $ref: '#/components/schemas/Product'