openapi: 3.0.3
info:
  title: NBG CIP Product API
  version: "0.1"
  description: This is the API for managing products in the NBG CIP system provided on the integration layer. It allows to create, update, delete and retrieve products and related customers. Find more information at [Swagger](http://swagger.io).
servers:
- url: https://api.server.test/v1
paths:
  /products:
    get:
      summary: Get all products
      operationId: products_get
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
      x-openapi-router-controller: swagger_server.controllers.product_controller
    post:
      summary: Create a new product
      operationId: products_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      x-openapi-router-controller: swagger_server.controllers.product_controller
  /products/query:
    get:
      summary: Query products based on parameters
      operationId: products_query
      parameters:
        - name: name
          in: query
          description: Filter products by name
          required: false
          schema:
            type: string
        - name: category
          in: query
          description: Filter products by category
          required: false
          schema:
            type: string
        - name: priceMin
          in: query
          description: Filter products with a minimum price
          required: false
          schema:
            type: number
            format: float
        - name: priceMax
          in: query
          description: Filter products with a maximum price
          required: false
          schema:
            type: number
            format: float
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
      x-openapi-router-controller: swagger_server.controllers.product_controller
  /products/{productId}:
    get:
      summary: Get a product by ID
      operationId: products_product_id_get
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      x-openapi-router-controller: swagger_server.controllers.product_controller
  /products/{productId}/children:
    post:
      summary: Add a child product to a parent product
      operationId: products_add_child
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the parent product
      requestBody:
        description: The child product to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        "201":
          description: Child product added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      x-openapi-router-controller: swagger_server.controllers.product_controller
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        category:
          type: string
        price:
          type: number
          format: float
        children:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    ProductList:
      type: array
      items:
        $ref: '#/components/schemas/Product'